name: comprehensive_pentest
version: "1.0.0"
description: |
  Comprehensive penetration testing workflow with 4 phases:
  1. Reconnaissance
  2. Vulnerability Scanning
  3. Exploitation (with approval)
  4. Post-Exploitation & Reporting
author: Nexus-CyberAgent Team
tags:
  - pentest
  - security
  - comprehensive

variables:
  - name: target
    type: string
    description: Target IP address or domain
    value: ""

  - name: aggressive_mode
    type: boolean
    description: Enable aggressive scanning
    value: false

  - name: max_severity
    type: string
    description: Minimum severity to report
    value: "medium"

triggers:
  - type: manual

steps:
  # Phase 1: Reconnaissance
  - id: recon_network
    name: Network Reconnaissance
    type: scan
    description: Discover open ports and services
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - nmap
        - masscan
      sandbox_tier: tier2
      config:
        timing: ${variables.aggressive_mode} ? 'aggressive' : 'normal'
        ports: "1-65535"
    timeout_seconds: 1800
    retry:
      max_attempts: 2
      delay_seconds: 60
    on_failure: stop

  - id: recon_web
    name: Web Reconnaissance
    type: scan
    description: Discover web technologies and endpoints
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - subfinder
        - httpx
        - katana
      sandbox_tier: tier2
    depends_on:
      - recon_network
    timeout_seconds: 1200
    on_failure: continue

  # Phase 2: Vulnerability Scanning
  - id: vuln_scan
    name: Vulnerability Scanning
    type: scan
    description: Identify vulnerabilities using multiple scanners
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - nuclei
        - nikto
        - sqlmap
      sandbox_tier: tier2
      config:
        severity: ${variables.max_severity}
        threads: 10
    depends_on:
      - recon_network
      - recon_web
    timeout_seconds: 3600
    retry:
      max_attempts: 1
      delay_seconds: 120
    on_failure: stop

  # Nexus Analysis After Scanning
  - id: nexus_analysis_scan
    name: AI-Powered Scan Analysis
    type: nexus_analysis
    description: Comprehensive AI analysis of scan results
    config:
      analysis_type: scan
      input_step: vuln_scan
      services:
        - graphrag
        - mageagent
        - orchestration
        - learning
        - spectrum
      autonomous: true
    depends_on:
      - vuln_scan
    timeout_seconds: 600
    on_failure: continue

  # Conditional: Check if critical vulnerabilities found
  - id: check_critical_vulns
    name: Check Critical Vulnerabilities
    type: condition
    description: Determine if critical vulnerabilities were found
    config:
      conditions:
        - field: vuln_scan.summary.by_severity.critical
          operator: gt
          value: 0
      on_true: notify_critical
      on_false: exploitation_approval
    depends_on:
      - vuln_scan

  # Notification for Critical Vulnerabilities
  - id: notify_critical
    name: Notify Critical Vulnerabilities
    type: notification
    description: Alert security team of critical findings
    config:
      channels:
        - email
        - slack
      recipients:
        - security-team@company.com
      subject: "CRITICAL: Vulnerabilities Found on ${variables.target}"
      message: |
        Critical vulnerabilities have been discovered during penetration testing.
        Target: ${variables.target}
        Critical Count: ${vuln_scan.summary.by_severity.critical}

        Please review immediately.
      data:
        execution_id: ${execution.execution_id}
        target: ${variables.target}
    depends_on:
      - check_critical_vulns
    on_failure: continue

  # Phase 3: Exploitation (Requires Approval)
  - id: exploitation_approval
    name: Exploitation Approval
    type: approval
    description: Request approval before attempting exploitation
    config:
      approvers:
        - security-lead
        - ciso
      message: |
        Approval required to proceed with exploitation phase.
        Target: ${variables.target}
        Vulnerabilities Found: ${vuln_scan.summary.vulnerabilities}
      timeout_minutes: 60
      auto_approve_after_timeout: false
    depends_on:
      - check_critical_vulns
      - nexus_analysis_scan

  - id: exploitation
    name: Controlled Exploitation
    type: scan
    description: Attempt exploitation of discovered vulnerabilities
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - metasploit
      sandbox_tier: tier2
      config:
        safe_mode: true
        timeout: 60
    depends_on:
      - exploitation_approval
    timeout_seconds: 1800
    on_failure: continue

  # Phase 4: Post-Exploitation & Reporting
  - id: nexus_analysis_full
    name: Comprehensive Nexus Analysis
    type: nexus_analysis
    description: Full AI analysis including exploitation results
    config:
      analysis_type: scan
      input_step: exploitation
      services:
        - graphrag
        - mageagent
        - orchestration
        - learning
        - spectrum
      autonomous: true
    depends_on:
      - exploitation
    timeout_seconds: 900
    on_failure: continue

  - id: generate_report
    name: Generate Executive Report
    type: report
    description: Comprehensive penetration testing report
    config:
      report_type: executive
      format: pdf
      include_steps:
        - recon_network
        - recon_web
        - vuln_scan
        - exploitation
        - nexus_analysis_full
      template: pentest_executive
    depends_on:
      - nexus_analysis_full
    on_failure: continue

  - id: generate_technical_report
    name: Generate Technical Report
    type: report
    description: Detailed technical findings report
    config:
      report_type: technical
      format: pdf
      include_steps:
        - recon_network
        - recon_web
        - vuln_scan
        - exploitation
        - nexus_analysis_full
      template: pentest_technical
    depends_on:
      - nexus_analysis_full
    on_failure: continue

  - id: export_results
    name: Export Results to SIEM
    type: export
    description: Export findings to SIEM for monitoring
    config:
      format: siem
      destination: https://siem.company.com/api/ingest
      include_steps:
        - vuln_scan
        - exploitation
        - nexus_analysis_full
      credentials: siem_api_key
    depends_on:
      - generate_report
      - generate_technical_report
    on_failure: continue

  # Final Notification
  - id: notify_completion
    name: Notify Completion
    type: notification
    description: Notify stakeholders of completion
    config:
      channels:
        - email
        - slack
      recipients:
        - security-team@company.com
      subject: "Penetration Test Complete: ${variables.target}"
      message: |
        Penetration testing workflow has completed successfully.

        Target: ${variables.target}
        Duration: ${execution.duration_seconds}s
        Total Findings: ${vuln_scan.summary.total_findings}
        Critical: ${vuln_scan.summary.by_severity.critical}
        High: ${vuln_scan.summary.by_severity.high}
        Medium: ${vuln_scan.summary.by_severity.medium}

        Reports have been generated and results exported to SIEM.
      data:
        execution_id: ${execution.execution_id}
    depends_on:
      - export_results
    on_failure: continue

notifications:
  on_success:
    - security-team@company.com
  on_failure:
    - security-team@company.com
    - ops-team@company.com
  on_completion:
    - audit-team@company.com

metadata:
  category: penetration-testing
  complexity: high
  estimated_duration: 7200
  required_approvals: 1
