name: malware_analysis_pipeline
version: "1.0.0"
description: |
  Comprehensive malware analysis pipeline with 5 phases:
  1. Static Analysis
  2. YARA Scanning
  3. Dynamic Analysis (Cuckoo Sandbox)
  4. Memory Forensics
  5. IOC Extraction & Threat Intelligence
author: Nexus-CyberAgent Team
tags:
  - malware
  - analysis
  - forensics

variables:
  - name: sample_hash
    type: string
    description: SHA256 hash of malware sample
    value: ""

  - name: enable_network
    type: boolean
    description: Enable network simulation for C2 analysis
    value: false

  - name: analysis_timeout
    type: number
    description: Timeout for dynamic analysis in seconds
    value: 600

triggers:
  - type: manual

steps:
  # Phase 1: Static Analysis
  - id: static_analysis
    name: Static Malware Analysis
    type: scan
    description: Analyze file structure, strings, and PE/ELF headers
    config:
      scan_type: malware
      target: ${variables.sample_hash}
      tools:
        - yara
        - clamav
        - pefile
        - strings
        - exiftool
        - radare2
      sandbox_tier: tier3
      config:
        deep_scan: true
    timeout_seconds: 600
    retry:
      max_attempts: 2
      delay_seconds: 30
    on_failure: stop

  # Phase 2: YARA Scanning
  - id: yara_scan
    name: YARA Rule Scanning
    type: scan
    description: Scan with 6000+ community YARA rules
    config:
      scan_type: malware
      target: ${variables.sample_hash}
      tools:
        - yara
      sandbox_tier: tier3
      config:
        rules_dir: /app/yara-rules
        generate_rule: true
    depends_on:
      - static_analysis
    timeout_seconds: 300
    on_failure: continue

  # Phase 3: Dynamic Analysis
  - id: dynamic_analysis
    name: Cuckoo Sandbox Analysis
    type: scan
    description: Execute malware in isolated VM environment
    config:
      scan_type: malware
      target: ${variables.sample_hash}
      tools:
        - cuckoo
      sandbox_tier: tier3
      config:
        timeout: ${variables.analysis_timeout}
        enable_network: ${variables.enable_network}
        vm_snapshot: win10_clean
        capture_memory: true
    depends_on:
      - static_analysis
      - yara_scan
    timeout_seconds: 900
    retry:
      max_attempts: 1
      delay_seconds: 60
    on_failure: stop

  # Phase 4: Memory Forensics
  - id: memory_forensics
    name: Volatility Memory Analysis
    type: scan
    description: Analyze memory dump for malicious code
    config:
      scan_type: malware
      target: ${variables.sample_hash}
      tools:
        - volatility
      sandbox_tier: tier3
      config:
        memory_dump: ${dynamic_analysis.output.memory_dump}
        plugins:
          - pslist
          - pstree
          - netscan
          - malfind
          - dlllist
          - handles
          - cmdline
          - filescan
    depends_on:
      - dynamic_analysis
    conditions:
      - field: dynamic_analysis.output.memory_dump
        operator: ne
        value: null
    timeout_seconds: 600
    on_failure: continue

  # Phase 5: IOC Extraction
  - id: ioc_extraction
    name: Extract Indicators of Compromise
    type: transform
    description: Extract and deduplicate IOCs from all analysis phases
    config:
      operation: extract_iocs
      sources:
        - static_analysis
        - yara_scan
        - dynamic_analysis
        - memory_forensics
      ioc_types:
        - ip
        - domain
        - url
        - file_hash
        - registry
        - mutex
        - file_path
    depends_on:
      - static_analysis
      - yara_scan
      - dynamic_analysis
      - memory_forensics
    on_failure: continue

  # Nexus Integration: Comprehensive Analysis
  - id: nexus_malware_analysis
    name: AI-Powered Malware Analysis
    type: nexus_analysis
    description: Multi-agent AI analysis with threat attribution
    config:
      analysis_type: malware
      input_step: ioc_extraction
      services:
        - graphrag
        - mageagent
        - orchestration
        - learning
        - spectrum
      autonomous: true
    depends_on:
      - ioc_extraction
    timeout_seconds: 1200
    on_failure: continue

  # Conditional: Check Threat Level
  - id: check_threat_level
    name: Assess Threat Level
    type: condition
    description: Determine if threat is critical
    config:
      conditions:
        - field: nexus_malware_analysis.overall_threat_score
          operator: gte
          value: 80
      on_true: notify_critical_threat
      on_false: generate_standard_report
    depends_on:
      - nexus_malware_analysis

  # Critical Threat Notification
  - id: notify_critical_threat
    name: Alert Critical Threat
    type: notification
    description: Immediate notification for critical threats
    config:
      channels:
        - email
        - slack
        - sms
      recipients:
        - security-team@company.com
        - soc-lead@company.com
      subject: "CRITICAL THREAT: Malware Analysis Complete"
      message: |
        Critical malware threat detected!

        Sample: ${variables.sample_hash}
        Threat Score: ${nexus_malware_analysis.overall_threat_score}/100
        Malware Family: ${nexus_malware_analysis.malware_family}
        Threat Actors: ${nexus_malware_analysis.attribution.threat_actors}

        IOCs: ${ioc_extraction.ioc_count} extracted
        Infrastructure: ${nexus_malware_analysis.attribution.infrastructure_map.nodes_count} nodes mapped

        Immediate action required!
    depends_on:
      - check_threat_level
    on_failure: continue

  # Generate Reports
  - id: generate_standard_report
    name: Generate Analysis Report
    type: report
    description: Comprehensive malware analysis report
    config:
      report_type: technical
      format: pdf
      include_steps:
        - static_analysis
        - yara_scan
        - dynamic_analysis
        - memory_forensics
        - ioc_extraction
        - nexus_malware_analysis
      template: malware_analysis
    depends_on:
      - check_threat_level
    on_failure: continue

  - id: generate_ioc_report
    name: Generate IOC Report
    type: report
    description: IOC list for threat hunting
    config:
      report_type: custom
      format: json
      include_steps:
        - ioc_extraction
        - nexus_malware_analysis
      template: ioc_list
    depends_on:
      - generate_standard_report
    on_failure: continue

  # Export to Threat Intelligence Platforms
  - id: export_to_misp
    name: Export to MISP
    type: export
    description: Export IOCs and analysis to MISP
    config:
      format: misp
      destination: https://misp.company.com/api
      include_steps:
        - ioc_extraction
        - nexus_malware_analysis
      credentials: misp_api_key
    depends_on:
      - generate_ioc_report
    on_failure: continue

  - id: export_to_siem
    name: Export to SIEM
    type: export
    description: Export findings to SIEM
    config:
      format: siem
      destination: https://siem.company.com/api/ingest
      include_steps:
        - static_analysis
        - dynamic_analysis
        - ioc_extraction
        - nexus_malware_analysis
      credentials: siem_api_key
    depends_on:
      - generate_ioc_report
    on_failure: continue

  # Block IOCs
  - id: block_iocs_approval
    name: Approval to Block IOCs
    type: approval
    description: Request approval to block IOCs at network perimeter
    config:
      approvers:
        - security-lead
        - network-admin
      message: |
        Approval required to block ${ioc_extraction.ioc_count} IOCs at network perimeter.

        Sample: ${variables.sample_hash}
        Threat Level: ${nexus_malware_analysis.overall_threat_score}

        IOCs will be blocked on:
        - Firewall
        - IDS/IPS
        - DNS filtering
        - Email gateway
      timeout_minutes: 30
      auto_approve_after_timeout: ${nexus_malware_analysis.overall_threat_score >= 90}
    depends_on:
      - export_to_misp
      - export_to_siem
    on_failure: continue

  # Final Notification
  - id: notify_completion
    name: Notify Analysis Complete
    type: notification
    description: Notify stakeholders of completion
    config:
      channels:
        - email
      recipients:
        - security-team@company.com
      subject: "Malware Analysis Complete: ${variables.sample_hash}"
      message: |
        Malware analysis pipeline has completed.

        Sample: ${variables.sample_hash}
        Duration: ${execution.duration_seconds}s
        Threat Score: ${nexus_malware_analysis.overall_threat_score}/100
        Malware Family: ${nexus_malware_analysis.malware_family}
        IOCs Extracted: ${ioc_extraction.ioc_count}
        Threat Actors: ${nexus_malware_analysis.attribution.threat_actors.length}

        Reports generated and IOCs exported to threat intelligence platforms.
    depends_on:
      - block_iocs_approval
    on_failure: continue

notifications:
  on_success:
    - security-team@company.com
  on_failure:
    - security-team@company.com
    - ops-team@company.com
  on_completion:
    - audit-team@company.com
    - threat-intel-team@company.com

metadata:
  category: malware-analysis
  complexity: high
  estimated_duration: 3600
  required_approvals: 1
  air_gapped: true
