name: vulnerability_assessment
version: "1.0.0"
description: |
  Quick vulnerability assessment workflow for regular security checks.
  Focuses on fast scanning with prioritized vulnerability reporting.
author: Nexus-CyberAgent Team
tags:
  - vulnerability
  - assessment
  - quick-scan

variables:
  - name: target
    type: string
    description: Target IP address, domain, or CIDR range
    value: ""

  - name: scan_depth
    type: string
    description: Scan depth (quick, standard, deep)
    value: "standard"

  - name: min_severity
    type: string
    description: Minimum severity to report
    value: "medium"

triggers:
  - type: manual
  - type: schedule
    config:
      schedule: "0 2 * * 0" # Weekly on Sunday at 2 AM

steps:
  # Step 1: Port Scanning
  - id: port_scan
    name: Port & Service Discovery
    type: scan
    description: Quick port scan to identify services
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - nmap
      sandbox_tier: tier2
      config:
        timing: ${variables.scan_depth == 'quick' ? 'fast' : 'normal'}
        ports: ${variables.scan_depth == 'deep' ? '1-65535' : 'top-1000'}
    timeout_seconds: ${variables.scan_depth == 'quick' ? 300 : 1200}
    retry:
      max_attempts: 2
      delay_seconds: 30
    on_failure: stop

  # Step 2: Vulnerability Scanning
  - id: vuln_scan
    name: Vulnerability Scanning
    type: scan
    description: Scan for known vulnerabilities
    config:
      scan_type: pentest
      target: ${variables.target}
      tools:
        - nuclei
        - nikto
      sandbox_tier: tier2
      config:
        severity: ${variables.min_severity}
        threads: ${variables.scan_depth == 'deep' ? 20 : 10}
        templates: ${variables.scan_depth == 'deep' ? 'all' : 'critical,high,medium'}
    depends_on:
      - port_scan
    timeout_seconds: ${variables.scan_depth == 'quick' ? 600 : 1800}
    on_failure: stop

  # Step 3: Nexus Analysis
  - id: nexus_analysis
    name: AI Vulnerability Analysis
    type: nexus_analysis
    description: Prioritize and analyze vulnerabilities with AI
    config:
      analysis_type: scan
      input_step: vuln_scan
      services:
        - graphrag
        - mageagent
        - orchestration
        - learning
      autonomous: true
    depends_on:
      - vuln_scan
    timeout_seconds: 300
    on_failure: continue

  # Step 4: Check for Critical Vulnerabilities
  - id: check_critical
    name: Check Critical Findings
    type: condition
    description: Determine if immediate action is needed
    config:
      conditions:
        - field: vuln_scan.summary.by_severity.critical
          operator: gt
          value: 0
      on_true: notify_urgent
      on_false: generate_report
    depends_on:
      - vuln_scan

  # Step 5: Urgent Notification
  - id: notify_urgent
    name: Urgent Security Alert
    type: notification
    description: Alert team of critical vulnerabilities
    config:
      channels:
        - email
        - slack
      recipients:
        - security-team@company.com
      subject: "URGENT: Critical Vulnerabilities Found - ${variables.target}"
      message: |
        Critical vulnerabilities discovered during vulnerability assessment.

        Target: ${variables.target}
        Critical: ${vuln_scan.summary.by_severity.critical}
        High: ${vuln_scan.summary.by_severity.high}

        Immediate remediation required!

        AI Analysis: ${nexus_analysis.overall_threat_level}
        Top Recommendations:
        ${nexus_analysis.recommended_actions}
    depends_on:
      - check_critical
      - nexus_analysis
    on_failure: continue

  # Step 6: Generate Report
  - id: generate_report
    name: Generate Assessment Report
    type: report
    description: Vulnerability assessment report
    config:
      report_type: technical
      format: pdf
      include_steps:
        - port_scan
        - vuln_scan
        - nexus_analysis
      template: vulnerability_assessment
    depends_on:
      - check_critical
      - nexus_analysis

  # Step 7: Export Results
  - id: export_results
    name: Export to Vulnerability Management
    type: export
    description: Export findings to vulnerability management platform
    config:
      format: json
      destination: https://vuln-mgmt.company.com/api/import
      include_steps:
        - vuln_scan
        - nexus_analysis
      credentials: vuln_mgmt_api_key
    depends_on:
      - generate_report
    on_failure: continue

  # Step 8: Completion Notification
  - id: notify_completion
    name: Assessment Complete
    type: notification
    description: Notify completion with summary
    config:
      channels:
        - email
      recipients:
        - security-team@company.com
      subject: "Vulnerability Assessment Complete: ${variables.target}"
      message: |
        Vulnerability assessment completed successfully.

        Target: ${variables.target}
        Scan Depth: ${variables.scan_depth}
        Duration: ${execution.duration_seconds}s

        Findings:
        - Critical: ${vuln_scan.summary.by_severity.critical}
        - High: ${vuln_scan.summary.by_severity.high}
        - Medium: ${vuln_scan.summary.by_severity.medium}
        - Low: ${vuln_scan.summary.by_severity.low}

        AI Threat Level: ${nexus_analysis.overall_threat_level}

        Report available in attachment.
    depends_on:
      - export_results

notifications:
  on_success:
    - security-team@company.com
  on_failure:
    - security-team@company.com
  on_completion:
    - audit-team@company.com

metadata:
  category: vulnerability-assessment
  complexity: medium
  estimated_duration: 1800
  required_approvals: 0
